export const ADD_PRODUCT_TO_BASKET = "ADD_PRODUCT_TO_BASKET";
export const GET_PRODUCT_COUNT_IN_BASKET = "GET_PRODUCT_COUNT_IN_BASKET";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const PRODUCT_REMOVED = "PRODUCT_REMOVED";
